### ISSUE TITLE
[BUG] Latest lolighter break 3.0 map

### ISSUE THREAD

**Issue by A-plou** [Loloppe/Lolighter#1] opened 2022-06-02 06:48 UTC
![image](https://user-images.githubusercontent.com/73841814/171569048-4751fd29-9551-40b0-bd90-bbf835011d00.png)

when trying to do a map and doing light with lolighter latest version, the file get somehow impossible to access. 
Happen to one of my map(accelerate) and one of Slayx map(rebuilding of paradise lost).

I believe the issue is from new settings or others thing, in any case Lolighter make it impossible to load the map (constant loading screen on a map in games). 
On Chromapper, we can see the light etc, but in games it's just infinite loading.

to fix it in games you need:
- create a new difficulty
- copy the block from the map that you made before on the new difficulty
- made your own light (update) or copy the light
- delete the old difficulty
- that will fix the map

**Comment by Loloppe** [comment] 2022-06-02 13:27
I've downloaded Slayx map (rebuilding of paradise lost), used Lolighter light generator on the map, saved as 3.0 file. I even tried to regenerate the whole file, everything work on my side. I can't reproduce your problem. If you have files that still does that, please send them to me.

**Comment by A-plou** [comment] 2022-06-02 17:50
[Accelerate.zip](https://github.com/Loloppe/Lolighter/files/8826275/Accelerate.zip)
this one have it 
![image](https://user-images.githubusercontent.com/73841814/171693576-74fb605a-f284-470b-a9e8-ca6ea03130bc.png)
![image](https://user-images.githubusercontent.com/73841814/171694703-d70d399a-af26-4d63-a8d0-cd86a9e94210.png)

**Comment by Loloppe** [comment] 2022-06-02 17:53
![image](https://user-images.githubusercontent.com/54846763/171695154-ed5caca2-6441-42ed-b05e-6b491ec9f0d0.png)
Work fine for me, latest BS version. Like I said, I can't reproduce the issue. Even if I remove the null value or not, null is allowed on Beat Saber right now.

**Comment by A-plou** [comment] 2022-06-02 17:54
then I have no idea why it doesn't work for me and slayx at this point, I'm on the latest version also 1.22.1

**Comment by Loloppe** [comment] 2022-06-02 17:57
If you remove the "null" in the .dat, does it load?

**Comment by A-plou** [comment] 2022-06-02 18:01
if I remove everything in baseEventTypeWithKeywords {}  (roginally with d:null) 
it perfectly work

**Comment by Loloppe** [comment] 2022-06-02 18:35
Does it work if you write it like this? 
![image](https://user-images.githubusercontent.com/54846763/171701960-44c214aa-5fcc-4594-8468-61dd5b102787.png)

**Comment by A-plou** [comment] 2022-06-02 18:41
yes it work

**Comment by Loloppe** [comment] 2022-06-02 18:52
Should be fixed now

**Closed as completed by Loloppe** 2022-06-02 18:52 UTC
